### ISSUE TITLE
Fails on non-latin (ex. emoji) URLs

### ISSUE THREAD

**Issue by towerofnix** [redirectatob/redirectatob.github.io#1]
Oops. Probably not much, if anything, can be done about this, without somewhat drastically changing the way redirectatob works! Which would mean complifying things.

Ex: http://🔝🍰.ws
As a workaround, *this* works: http://xn--nj8hz0a.ws/ – so no big deal.

Chrome will convert the first example into the second example:

![Location bar emoji-conversion screenshot](https://cloud.githubusercontent.com/assets/9948030/24730396/d29cc9a8-1a39-11e7-9f10-9e27070b2b8f.png)

Do other browsers display/keep the fancy emoji things in URLs in the location bar?

I'd have to do more research on how these emoji-URLs work.

**Comment by joker314** [comment]
_Eww_ Chrome!
###### Says the person writing this in Chrome

Okay, so, here's how we could do it.

## Encoding

1) Request URL as input
2) Run `encodeURIComponent`
3) Run `btoa`

## Decoding

1) Extract base64-encoded content through hash
2) Run `atob`
3) Run `decodeURIComponent`
4) Run security checks
5) Redirect

By encoding the URL as if _all_ of it is after the domain part; the entire string is composed of the normal Latin1 characters (with the special characters replaced with percentage signs followed by two hexadecimal digits).

Decoding the URL as if _all_ of it is after the domain part preserves the emojis. Yay!

## Problems

Existing URLs which rely on percentage encoding will be decoded even though they're not supposed to be. New ones will be double encoded so they aren't a problem.

## How to fix

Before the URL, a `!` could be placed to indicate that the URL has been URL encoded before `btoa`ing. This allows new URLs which do not contain non-Latin characters to be shorter when encoded, as a bonus.

## Summary of solution

### To encode

```javascript
let url = prompt("Enter URL plz!");
let encoded;
try{
  encoded = btoa(url) // Try to use old method of encoding
} catch (err) {
  encoded = btoa(encodeURIComponent("!" + url)); // Flag with "!", then URL encode to avoid non-Latin characters
}
```

### To decode

```javascript
let url = location.hash;
let decoded;
decoded = atob(url); // Normally decode
if(decoded[0] === "!") // But if the flag is present
  decoded = decodeURIComponent(url.substr(1)); // Then strip the flag and URL decode
```
