### ISSUE TITLE
Change <input> type to 'url'

### ISSUE THREAD

**Issue by joker314** [redirectatob/redirectatob.github.io#12]
Currently, the `<input>` element's type is set to the default, `text`.

https://github.com/redirectatob/redirectatob.github.io/blob/2f39801e454417f970243762fa10d108adf3c081/make.html#L13

However, we're actually expecting a URL. If the type is set to ['url'](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url), then mobile users will be prompted with a special keyboard that _might_ have <kbd>.com</kbd> and <kbd>https://</kbd> as single keys.

If a browser does not support `'url'`, the fallback of `'text'` is used -- so this won't break anything.

However, a browser may perform basic validation. We probably need to confirm that this validation does not prevent exotic URLs from braking. We can probably safely assume that normal URLs will work. Hence, this set of tests focuses on unusual URLs.
- [X] Chrome
  - [X] data:text/plain,Hello
  - [X] http://🔝🍰.ws
- [x] Firefox
  - [x] data:text/plain,Hello
  - [x] http://🔝🍰.ws
- [x] Opera
  - [x] data:text/plain,Hello
  - [x] http://🔝🍰.ws
- [x] Safari
  - [x] data:text/plain,Hello
  - [x] http://🔝🍰.ws
- [x] IE
  - [x] data:text/plain,Hello
  - [x] http://🔝🍰.ws
- [x] Edge
  - [x] data:text/plain,Hello
  - [x] http://🔝🍰.ws

<hr>

What is the earliest version of IE we are aiming to support?

**Comment by towerofnix** [comment]
Updated with Firefox tests done - the two entries still work. (And when I type "asdf", it shows "Please enter a URL.")

>What is the earliest version of IE we are aiming to support?

No particular statement. Officially, I want to support Edge, and perhaps the *latest* version of IE.

**Comment by towerofnix** [comment]
Just tested with IE 11. Both cases work, although I had to change the line `startsWith("!")` to `[0] === '!'` to make redirects work (IE doesn't have `startsWith`).

**Comment by joker314** [comment]
Yep, just had a similar experience. I'll get Opera installed and test that next

**Comment by towerofnix** [comment]
Tried Edge - it works fine.

**Comment by towerofnix** [comment]
Safari also works; also, I tested with mobile, and the `.com`, `:`, and `/` keys were made available. Handy and exactly what's wanted here! :tada:
