### ISSUE TITLE
Make HTML valid

### ISSUE THREAD

**Issue by towerofnix** [redirectatob/redirectatob.github.io#16]
Basically just substitute `<element attr='value'>` with `<element attr="value">` - single quotes aren't valid HTML.

**Comment by towerofnix** [comment]
Apparently single quotes *are* valid, but.. I mean.. double quotes look better. I'm going to make a PR for this anyways.

**Comment by joker314** [comment]
This could be a good time to remove all the semicolons in the JS per https://github.com/redirectatob/redirectatob.github.io/pull/4#discussion_r167685260 -- but maybe not

**Comment by towerofnix** [comment]
@joker314 Good thinking, but I think I'll leave them there. No awfully deep or practical reason or anything; it just.. Feels Right to me. Weird.

**Comment by towerofnix** [comment]
Resolved in #19.
