### ISSUE TITLE
Should this repository be free?

### ISSUE THREAD

**Issue by joker314** [redirectatob/redirectatob.github.io#17]
There's no LICENCE file -- and this is an absolutely valid thing to do. However, it also has some drawbacks. Should this repository be released under a libre software licence?

**Comment by towerofnix** [comment]
Oh, absolutely. I'm all for GPL. Thanks for bringing this up!

**Comment by towerofnix** [comment]
Would you like to make a PR for this?

**Comment by joker314** [comment]
Sure!
