### ISSUE TITLE
Invalid URLs can be used to generate redirects

### ISSUE THREAD

**Issue by R4356th** [redirectatob/redirectatob.github.io#27]
This is not a big issue but should it actually stay untouched?

**Comment by towerofnix** [comment]
Huh, if you still recall (sorry it's been ages :P) could you give me an example invalid URL? There's already error-handling code in make.html, so I'm not too sure what you're talking about, sorry!

**Comment by R4356th** [comment]
I am afraid I am indeed not sure what the URL was. My mind keeps telling me it was a URL without any protocol but I am unable to reproduce this behaviour at the moment. I will just close this issue for now and will reopen if I recall what the URL was.

(The issue may have also been fixed because of browser updates.)

**Comment by towerofnix** [comment]
Alright, thanks! Definitely feel encouraged to let me know if you spot anything like this!
